### ISSUE TITLE
Add project configuration file

### ISSUE THREAD

**Issue by dbalcomb** [ploys/ploys#48]
The project would benefit from using a `Ploys.toml` project configuration file to get project information and configuration in a consistent way.

The current implementation of the `Source` trait has methods for getting the project name and URL. This currently uses the directory or repository name for the project name, and origin remote or repository URL for the URL. Although these can be computed, there is no guaranteed consistency between the different sources and there is the possibility that the repository name or directory name could be altered which may break some of the planned flows.

An example of a project configuration file is as follows:

```toml
[project]
name = "ploys"
source = "https://github.com/ploys/ploys"

[packages.ploys]
type = "cargo"
path = "packages/ploys"

[packages.ploys-api]
type = "cargo"
path = "packages/ploys-api"

[packages.ploys-cli]
type = "cargo"
path = "packages/ploys-cli"
```

The initial implementation may only support the `name` and `source` fields but the introduction of the `packages` section may reduce the number of file system calls or network requests to discover the information. The configuration file can then become the source of truth for project configuration with additional commands such as `ploys package add` and `ploys package rename` to manage the project's packages.
