### ISSUE TITLE
Add `install` command

### ISSUE THREAD

**Issue by dbalcomb** [ploys/ploys#89]
## Idea

We want to support using tools like `tarpaulin` or `cargo-semver-checks` as part of the various flows and in the GitHub Actions workflow. To do this we should provide our own `install` command and GitHub Action that invokes the command to install these tools.

## Motivation

The primary reason for incorporating this into the project is to create reproducible flows and this is not something that other tools address. This would mean that the command is aware of the version control system and timestamp of the current commit. Using the timestamp, the tool can install the version at a specific point in time. This is particularly useful for GitHub Actions workflows to re-run a job without producing different results.

An example of this is using a different version of `clippy` with different lints. Although unlikely, it is possible that a new lint lands between the final commit and a merge, causing `clippy` to fail on the merge commit. It is also possible that an accidental regression lands in Rust itself but that should be resolved with a patch release if we permit those and wait long enough to retry.

## Implementation

The project should maintain a list of commonly used tools and provide a `ploys install TOOL_NAME@VERSION` command that allows users to install a specific version of a tool. It should also support additional user-configured tools to ensure that the project can install all the required dependencies without custom scripts.

### Custom Tools

Using the configuration file in #48 (but now as YAML instead of TOML), we can specify custom tools that can be installed from different sources. The following is an example of what this might look like:

```yaml
tools:
  # Install from a GitHub release
  tarpaulin:
    from: github
    with:
      repository: xd009642/tarpaulin
      release: latest
      file: |
        cargo-tarpaulin-{target}.{extension}
        cargo-tarpaulin-{version}-travis.tar.gz

  # Install from crates.io (or via cargo-quickinstall release)
  tarpaulin:
    from: crates.io
    with:
      crate: cargo-tarpaulin

  # Install from url
  tarpaulin:
    from: url
    with:
      url: |
        https://github.com/xd009642/tarpaulin/releases/download/{version}/cargo-tarpaulin-{target}-travis.{extension}
        https://github.com/xd009642/tarpaulin/releases/download/{version}/cargo-tarpaulin-{version}-travis.tar.gz
```

This structure reflects the GitHub Actions workflow step format where arguments are supplied under the `with` field but the specifics can be worked out later.

Both the `github` and `url` sources use variable replacement and provide multiple options for getting the file. When this was initially thought up the `cargo-tarpaulin` releases used a non-standard asset name so there should be fallback functionality but there may be a better way using version constraints.

### Action

The following is an example of what an `install` action might look like:

```yaml
steps:
- name: Install
  uses: ploys/install@1
  with:
    tools: tarpaulin@0.21, make, udeps
```

The action should support the GitHub Actions tool cache to load and store these tools. Although they will not persist between runs on GitHub-hosted runners it is possible that some of these tools will already be in the cache. It is also possible that a tool will be required in multiple steps and a composite action may try to reinstall the tool but this can be loaded from the tool cache on subsequent installs.

## Similar Projects

* [cargo-quickinstall](https://crates.io/crates/cargo-quickinstall)
* [cargo-binstall](https://crates.io/crates/cargo-binstall)

The above projects are rust-specific but this project aims to be more general. It should be possible to integrate the `cargo-quickinstall` release registry as `cargo-binstall` does as a specific source.
